sudo: required
dist: xenial

services:
  - docker
  - xvfb

addons:
    chrome: "stable"
    apt:
      packages:
        - unixodbc-dev # required for pyodbc

language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements/$TRAVIS_PYTHON_VERSION.txt

before_script: # add the mssql driver for xenial
  - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
  - sudo apt-get -qq update
  - sudo ACCEPT_EULA=Y apt-get -y install msodbcsql17

script:
  - flake8
  - sphinx-build -nW docs docs/_build/html
  - py.test -sv --cov-config .coveragerc --cov-report html:skip-covered --cov-report term:skip-covered --cov=testcontainers --tb=short tests/
  - codecov

notifications:
  email:
    recipients:
      - sergio_89@ukr.net
